[toolchain]
channel = "nightly-2023-02-01" # 1.69
components = [
    # For components/script_plugins, https://github.com/rust-lang/rust/pull/67469
    "rustc-dev",
    "rustfmt",
]
profile = "minimal"
